annotation_path: Data_inspect/neuron_category.pkl
csv_paths:
  signed: data/droso_data/signed_connectivity_matrix.csv
  unsigned: data/droso_data/ad_connectivity_matrix.csv
signed: true
sio: true
rescale_factor: 0.04

result_path: results-chess

policy: state_value
train_num_sample: 2560000
timesteps: 10 # for timesteps in [2,5,10,15]:
num_epoch: 10
batch_size: 256
#num_trials: 5

# This is the part sent to tokenizer
data:
  data_choice: chess_SV
  use_bucket: false

experiments:
  DPU_Base_Unlearnable:
    init: droso
    trainable: false
    drop_out: true
    model_choice: basicrnn
    input_type: sensory
    output_type: output
  DPU_CNN_Unlearnable:
    init: droso
    trainable: false
    drop_out: true
    model_choice: basicCNN
    filter_num: 1 # number of set of filters used in CNN probably 1 or 2.
    input_type: sensory
    output_type: output
  DPU_CNN_Unlearnable_RELU: # add relu after conv layers
    init: droso
    trainable: false
    drop_out: true
    model_choice: basicCNN
    filter_num: 1 # number of set of filters used in CNN probably 1 or 2.
    use_relu: true
    input_type: sensory
    output_type: output





  DPU_Base_Unlearnable_residual:
    init: droso
    trainable: false
    drop_out: true
    residual: true
    model_choice: basicrnn
    input_type: sensory
    output_type: output
  DPU_CNN_Unlearnable_residual:
    init: droso
    trainable: false
    drop_out: true
    residual: true
    model_choice: basicCNN
    filter_num: 1 # number of set of filters used in CNN probably 1 or 2.
    input_type: sensory
    output_type: output
  DPU_CNN_Unlearnable_RELU_residual: # add relu after conv layers
    init: droso
    trainable: false
    drop_out: true
    residual: true
    model_choice: basicCNN
    filter_num: 1 # number of set of filters used in CNN probably 1 or 2.
    use_relu: true
    input_type: sensory
    output_type: output




  DPU_Base_Unlearnable_cumulative:
    init: droso
    trainable: false
    drop_out: true
    cumulative: true
    model_choice: basicrnn
    input_type: sensory
    output_type: output
  DPU_CNN_Unlearnable_cumulative:
    init: droso
    trainable: false
    drop_out: true
    cumulative: true
    model_choice: basicCNN
    filter_num: 1 # number of set of filters used in CNN probably 1 or 2.
    input_type: sensory
    output_type: output
  DPU_CNN_Unlearnable_RELU_cumulative: # add relu after conv layers
    init: droso
    trainable: false
    drop_out: true
    cumulative: true
    model_choice: basicCNN
    filter_num: 1 # number of set of filters used in CNN probably 1 or 2.
    use_relu: true
    input_type: sensory
    output_type: output