# Global configuration
result_path: "results"  # Path to save results and models
signed: true
sio: true # sio: sensory-interneuron-output
fewshot:
  enabled: false # options: true for  few-shot training, false for full training
  samples: 60 # options: 60 for 1%, 120 for 2%, 300 for 5%, 600 for 10%
  batch_size: 17
num_trials: 3
num_epochs: 10
batch_size: 64
learning_rate: 0.003
dropout_rate: 0.1

# Paths for connectivity data
csv_paths:
  signed: "data/signed_connectivity_matrix.csv"
  unsigned: "data/ad_connectivity_matrix.csv"
annotation_path: "data/science.add9330_data_s2.csv"
rescale_factor: 0.04

# Experiment definitions
experiments:  

  # ------------------------------------------------------------------------------------------------
  # Multi-Sensory Fusion Experiments
  # ------------------------------------------------------------------------------------------------
  
  MultiSensory_Temporal_Fusion:
    type: multisensoryrnn
    trainable: false
    init: droso
    sensory_types:  # List of sensory types to use
      - visual
      - olfactory
      - gustatory-external
      - respiratory
      - gut
    time_steps:
      visual: 4
      olfactory: 3
      gustatory-external: 3
      respiratory: 2
      gut: 2
    embedding_dim: 128
    decision_hidden_dim: 256

  # ------------------------------------------------------------------------------------------------
  # Main Experiments
  # ------------------------------------------------------------------------------------------------

  # # 1. DPU-LORA: rather than fine-tuning the DPU, do the LORA thing, where we literally add a low-rank matrix to it
  # DPU_LoRA:
  #   type: basicrnn
  #   trainable: false  # Keep DPU weights frozen
  #   init: droso
  #   lora:
  #     enabled: true
  #     rank: 8      # r parameter from LoRA paper
  #     alpha: 16    # alphax scaling factor

  # # 2. unlearnable DPU
  # Unlearnable_DPU:
  #   type: basicrnn
  #   trainable: false
  #   init: droso

  # # 3. learnable RNN (maintaining the same sparsity, but not the same sparsity pattern)
  # Learnable_RNN_Same_Sparsity: 
  #   type: basicrnn
  #   trainable: true
  #   init: permuted
  #   pruning: true
  #   lambda_l1: 0.0001

  # # 4. unlearnable RNN (maintaining the same sparsity, but not the same sparsity pattern)
  # Unlearnable_RNN_Same_Sparsity:
  #   type: basicrnn
  #   init: permuted
  #   trainable: false
  #   pruning: false

  # # 5. learnable RNN (no sparsity)
  # Learnable_RNN_No_Sparsity:
  #   type: basicrnn
  #   trainable: true
  #   init: random
  #   pruning: true
  #   lambda_l1: 0.0001

  # # 6. unlearnable RNN (no sparsity)
  # Unlearnable_RNN_No_Sparsity:
  #   type: basicrnn
  #   trainable: false
  #   init: random

  # # 7. Unlearnable MLP (3 hidden layer, same total weight as droso)
  # Unlearnable_Threehidden_MLP:
  #   type: threehiddenmlp
  #   freeze: true

  # # 8. Learnable MLP (3 hidden layer, same total weight as droso)
  # Learnable_Threehidden_MLP:
  #   type: threehiddenmlp
  #   freeze: false

  # # # 9. Unlearnable MLP (2 hidden layer, same total weight as droso)
  # Unlearnable_Twohidden_MLP:
  #   type: twohiddenmlp
  #   freeze: true

  # ------------------------------------------------------------------------------------------------
  # Accuracy Leveraging Experiments
  # ------------------------------------------------------------------------------------------------

  # DPU_LoRA_Accuracy_Leveraging:
  #   type: basicrnn
  #   trainable: false  # Keep DPU weights frozen
  #   init: droso
  #   lora:
  #     enabled: true
  #     rank: 8      # r parameter from LoRA paper
  #     alpha: 16    # alphax scaling factor
  #   sensory_type: all

  # Unlearnable_CNN_DPU_Accuracy_Leveraging:
  #   type: basicrnn
  #   trainable: false
  #   init: droso
  #   sensory_type: all
  #   use_cnn_features: true

  # Unlearnable_DPU_Accuracy_Leveraging:
  #   type: basicrnn
  #   trainable: false
  #   init: droso
  #   sensory_type: all


  # Unlearnable_RNN_Same_Sparsity_Accuracy_Leveraging:
  #   type: basicrnn
  #   init: permuted
  #   trainable: false
  #   pruning: false
  #   sensory_type: all

  # Unlearnable_RNN_No_Sparsity_Accuracy_Leveraging:
  #   type: basicrnn
  #   trainable: false
  #   init: random
  #   sensory_type: all

  # ------------------------------------------------------------------------------------------------
  # Initialization Experiments
  # ------------------------------------------------------------------------------------------------
    
  # # 7. Learnable RNN with row-permuted initialization
  # Learnable_RNN_Row_Permuted:
  #   type: basicrnn
  #   trainable: true
  #   init: row_permuted
  #   pruning: true
  #   lambda_l1: 0.0001
    
  # # 8. Unlearnable RNN with row-permuted initialization
  # Unlearnable_RNN_Row_Permuted:
  #   type: basicrnn
  #   trainable: false
  #   init: row_permuted
    
  # # 9. Learnable RNN with column-permuted initialization
  # Learnable_RNN_Col_Permuted:
  #   type: basicrnn
  #   trainable: true
  #   init: col_permuted
  #   pruning: true
  #   lambda_l1: 0.0001
    
  # # 10. Unlearnable RNN with column-permuted initialization
  # Unlearnable_RNN_Col_Permuted:
  #   type: basicrnn
  #   trainable: false
  #   init: col_permuted
    
  # # 11. Learnable RNN with eigenvalue-matched initialization
  # Learnable_RNN_Eigenvalue_Matched:
  #   type: basicrnn
  #   trainable: true
  #   init: eigenvalue_matched
  #   pruning: true
  #   lambda_l1: 0.0001
    
  # # 12. Unlearnable RNN with eigenvalue-matched initialization
  # Unlearnable_RNN_Eigenvalue_Matched:
  #   type: basicrnn
  #   trainable: false
  #   init: eigenvalue_matched
    
  # # 13. Learnable RNN with eigenvalue-permuted initialization
  # Learnable_RNN_Eigenvalue_Permuted:
  #   type: basicrnn
  #   trainable: true
  #   init: eigenvalue_permuted
  #   pruning: true
  #   lambda_l1: 0.0001
    
  # # 14. Unlearnable RNN with eigenvalue-permuted initialization
  # Unlearnable_RNN_Eigenvalue_Permuted:
  #   type: basicrnn
  #   trainable: false
  #   init: eigenvalue_permuted

  # # # # 15. Unlearnable RNN with same eigenvalues and same eigenvectors initialization
  # Unlearnable_RNN_Low_Rank:
  #   type: basicrnn
  #   trainable: false
  #   init: same_eigenvalues_same_eigenvectors
  #   sensory_type: all
  #   explained_variance: 0.1

  # # # 16. Unlearnable RNN with same eigenvalues and random eigenvectors initialization
  # Unlearnable_RNN_Random_Structure_Same_Spectrum:
  #   type: basicrnn
  #   trainable: false
  #   init: same_eigenvalues_random_eigenvectors
  #   sensory_type: all
  #   explained_variance: 0.1

  # # # 17. Unlearnable RNN with random eigenvalues and same eigenvectors initialization
  # Unlearnable_RNN_Random_Singular_Values:
  #   type: basicrnn
  #   trainable: false
  #   init: random_eigenvalues_same_eigenvectors
  #   sensory_type: all
  #   explained_variance: 0.1

  # # # 18. Unlearnable RNN with identical eigenvalues and same eigenvectors initialization
  # Unlearnable_RNN_Identical_Singular_Values:
  #   type: basicrnn
  #   trainable: false
  #   init: identical_eigenvalues_same_eigenvectors
  #   sensory_type: all
  #   explained_variance: 0.1

  # # # 19. Unlearnable RNN with random eigenvalues and random eigenvectors initialization
  # Unlearnable_RNN_Random_Singular_Values_Random_Spectrum:
  #   type: basicrnn
  #   trainable: false
  #   init: random_eigenvalues_random_eigenvectors
  #   sensory_type: all
  #   explained_variance: 0.1

  # ------------------------------------------------------------------------------------------------
  # Sensory Type Experiments, using the same model as the main experiments, but with different sensory inputs, which includes:
  # 1. olfactory
  # 2. visual
  # 3. gut
  # 4. respiratory
  # 5. gustatory-external
  # 6. all
  # ------------------------------------------------------------------------------------------------

  # # Olfactory Sensory Input
  # Unlearnable_Olfactory_DPU:
  #   type: basicrnn
  #   trainable: false
  #   init: droso
  #   sensory_type: olfactory
  #   time_steps: 3  # Number of time steps for RNN forward pass

  # # Visual Sensory Input
  # Unlearnable_Visual_DPU:
  #   type: basicrnn
  #   trainable: false
  #   init: droso
  #   sensory_type: visual
  #   time_steps: 4 

  # # Gut Sensory Input
  # Unlearnable_Gut_DPU:
  #   type: basicrnn
  #   trainable: false
  #   init: droso
  #   sensory_type: gut

  # # Respiratory Sensory Input
  # Unlearnable_Respiratory_DPU:
  #   type: basicrnn
  #   trainable: false
  #   init: droso
  #   sensory_type: respiratory

  # # Gustatory-external Sensory Input
  # Unlearnable_Gustatory_DPU:
  #   type: basicrnn
  #   trainable: false
  #   init: droso
  #   sensory_type: gustatory-external

  # # All Sensory Inputs
  # Unlearnable_All_Sensory_DPU:
  #   type: basicrnn
  #   trainable: false
  #   init: droso
  #   sensory_type: all
